comments/urls.py
from django.urls import path

from comments import views


app_name = "comments"

urlpatterns = [
    path("", views.comments)
]

foodie/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("sandbox/", include("sandbox.urls")),
    path("", include("foodie_app.urls")),
    path("recipes/", include("recipes.urls")),
    path("comments/", include("comments.urls")),
]

foodie_app/urls.py
from django.urls import path
from . import views


app_name = "foodie_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("recipes/<int:category_id>/", views.recipes, name="recipes"),
    path("add-category/", views.add_category, name="add_category"),
    path("add-recipe/", views.add_recipe, name="add_recipe_no_genre"),
    path("add-recipe/category/<int:category_id>/", views.add_recipe, name="add_recipe_with_genre")
]

recipes/urls.py
from django.urls import path

from recipes import views


app_name = "recipes"

urlpatterns = [
    path("", views.recipes, name="index"),
    path("<int:recipe_id>", views.recipe, name="recipe_detail")
]

sandbox/urls.py
from django.urls import path
from . import views
from sandbox.views import RecipeDetailView, RecipeListView, SpecificRecipesView

app_name = "sandbox"

urlpatterns = [
    path("", views.index, name="index"),
    path("recipes/", views.RecipeListView.as_view(), name="recipe_list"),
    path("recipes/<int:pk>", views.RecipeDetailView.as_view(), name="recipe_detail"),
    path("refreshing/", views.SpecificRecipesView.as_view(), name="refreshing_recipes"),
    path("feedback", views.feedback, name="feedback"),
    path("thank-you", views.thank_you, name="thank_you")
]

comments/models.py
from django.db import models

from recipes.models import Recipe

# Create your models here.
class Comment(models.Model):
  recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
  text = models.TextField()
  date_added = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
      return self.text
  

foodie_app/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
  name = models.CharField(max_length=100)
  date_added = models.DateField(auto_now_add=True, blank=True)
  
  class Meta:
    ordering = ['date_added']
    verbose_name = "Category"
    verbose_name_plural = "Categories"
  
  def __str__(self):
      return self.name
  
  
  
  

recipes/models.py
from django.db import models

from foodie_app.models import Category

# Create your models here.
class Recipe(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(null=True, blank=True)
  ingredients = models.TextField()
  directions = models.TextField()
  date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True)

  category = models.ForeignKey(Category, on_delete=models.CASCADE)
  
  def __str__(self):
      return self.name

sandbox/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
  name = models.CharField(max_length=100)
  email = models.EmailField()
  feedback = models.TextField()
  satisfaction = models.CharField(max_length=10)
  
  def __str__(self):
      return self.name
  

comments/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def comments(request):
  return HttpResponse("Hello From Comments")

foodie_app/views.py
from django.shortcuts import get_object_or_404, redirect, render

from foodie_app.form import CategoryForm, RecipeForm
from .models import Category
from recipes.models import Recipe

# Create your views here.
def index(request):
  categories = Category.objects.all()
  context = {"categories": categories}
  
  return render(request, "foodie_app/index.html", context)

def recipes(request, category_id):
  recipes = Recipe.objects.filter(category=category_id)
  category = Category.objects.get(pk=category_id)
  
  context = {"recipes": recipes, "category": category}
  
  return render(request, "foodie_app/recipes.html", context)

def add_category(request):
  if request.method == "POST":
    form = CategoryForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect("foodie_app:index")
    else:
      return render(request, "foodie_app/add_category.html")
  else:
    form = CategoryForm()
    context = {"form": form}
    return render(request, "foodie_app/add_category.html", context)

def add_recipe(request, category_id=None):
  category = None
  if category_id:
    category = get_object_or_404(Category, id=category_id)
    form = RecipeForm(request.POST or None, initial={"category": category})
  else:
    form = RecipeForm(request.POST or None)
  
  if request.method == 'POST' and form.is_valid():
    new_recipe = form.save()
    return redirect("foodie_app:recipes", category_id=new_recipe.category.id)
  
  context = {
    "form": form,
    "category": category
  }
  return render(request, "foodie_app/add_recipe.html", context)
  

recipes/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Q

from foodie_app.form import RecipeForm
from foodie_app.models import Category

from .models import Recipe

# Create your views here.
def recipes(request):
  recipes = Recipe.objects.all()
  context = {"recipes": recipes}

  
  return render(request, "recipes/recipes.html", context)

def recipe(request, recipe_id):
  recipe = Recipe.objects.get(id=recipe_id)
  context = {"recipe": recipe}
  
  return render(request, "recipes/recipe.html", context)
    
        

sandbox/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import ListView, DetailView

from recipes.models import Recipe
from sandbox.form import FeedbackForm
from sandbox.models import Feedback

# Create your views here.
def index(request):
  recipes = Recipe.objects.all()
  
  context = {"recipes": recipes}
  return render(request, "sandbox/index.html", context)

class RecipeListView(ListView):
  model = Recipe
  template_name = "sandbox/index.html"
  context_object_name = "recipes"
  
  def get_queryset(self):
    filtered_recipes = Recipe.objects.filter(category__name__iexact="soup")
    return filtered_recipes

class RecipeDetailView(DetailView):
  model = Recipe
  template_name = "sandbox/recipe_detail.html"
  context_object_name = "recipe"
  
class SpecificRecipesView(View):
  def get(self, request, *args, **kwargs):
    # fetch recipes with 'refreshing" in the description
    refreshing_recipes = Recipe.objects.filter(description__icontains="refreshing")
    context = {"refreshing": refreshing_recipes}
    return render(request, "sandbox/refreshing_recipe.html", context)
  
def thank_you(request):
  return HttpResponse("Thank you for your feedback")
  
def feedback(request):
  if request.method == "POST":
    form = FeedbackForm(request.POST)
    if form.is_valid():
      # process the form
      print(form.cleaned_data)
      name = form.cleaned_data["name"]
      email = form.cleaned_data["email"]
      feedback = form.cleaned_data["feedback"]
      satisfaction = form.cleaned_data["satisfaction"]
      Feedback.objects.create(
        name=name,
        email=email,
        feedback=feedback,
        satisfaction=satisfaction
      )
      return redirect('sandbox:thank_you')
  else:
    form = FeedbackForm()
    
  context = {"form": form}
  return render(request, "sandbox/feedback_form.html", context)

foodie_app/templates/foodie_app/add_category.html
{% extends "base.html" %}

{% block content %}
  <h3>Add Category</h3>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
  </div>
{% endblock content %}

foodie_app/templates/foodie_app/add_recipe.html
{% extends "base.html" %}

{% block content %}
  <h3>Add a new Recipe
    {% if category %}to
      {{ category.name }}
    {% endif %}
  </h3>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save Recipe</button>
    </form>
  </div>
{% endblock content %}

foodie_app/templates/foodie_app/index.html
{% extends "base.html" %}

{% block content %}
  <h3>Categories</h3>
  <div>
    <a href="{% url "foodie_app:add_category" %}">Add Categories</a>
    {% for category in categories %}
      <div>
        <a href="{% url "foodie_app:recipes" category.id %}">{{ category.name }}</a>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

foodie_app/templates/foodie_app/recipes.html
{% extends "base.html" %}

{% block content %}
  <h3>Recipes under
    <i>{{ category }}</i>
  </h3>
  <a href="{% url "foodie_app:add_recipe_with_genre" category_id=category.id %}">Add Recipe</a>
  <div>
    {% for recipe in recipes %}
      <div>
        <h5>{{ recipe.name }}</h5>
        <p>{{ recipe.description }}</p>
        {% comment %} <a href="">{{ category }}</a> {% endcomment %}
      </div>
    {% endfor %}
  </div>
{% endblock content %}

recipes/templates/recipes/recipe.html
{% extends "base.html" %}

{% block content %}
  <div>
    <div>
      <h5>{{ recipe.name }}</h5>
      <i>Description:</i>
      <p>{{ recipe.description }}</p>
      <i>Ingredients:</i>
      <p>{{ recipe.ingredients }}</p>
      <i>Directions:</i>
      <p>{{ recipe.directions }}</p>
    </div>
  </div>
{% endblock content %}

recipes/templates/recipes/recipes.html
{% extends "base.html" %}

{% block content %}
  <div>
    {% for recipe in recipes %}
      <div>
        <h5>{{ recipe.name }}</h5>
        <p>{{ recipe.description }}</p>
        <a href="{% url "recipes:recipe_detail" recipe.id %}">View Recipe Details</a>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

sandbox/templates/sandbox/feedback_form.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock content %}

sandbox/templates/sandbox/index.html
{% extends "base.html" %}

{% block content %}
  {% if foods %}
    <ul>
      {% for food in foods %}
        <li>{{ food }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No foods found.</p>
  {% endif %}
{% endblock content %}

sandbox/templates/sandbox/recipe_detail.html
{% extends "base.html" %}

{% block content %}
  {% if recipe %}
    <article>
      <h2>{{ recipe.name }}</h2>
      Ingredients:
      <p>{{ recipe.ingredients }}</p>
      Description:
      <p>{{ recipe.description }}</p>
      Directions:
      <p>{{ recipe.directions }}</p>
    </article>
  {% else %}
    <p>No recipes found.</p>
  {% endif %}
{% endblock content %}

sandbox/templates/sandbox/refreshing_recipe.html
{% extends "base.html" %}

{% block content %}
  {% if refreshing %}
    <ul>
      {% for recipe in refreshing %}
        <li>
          <a href="{% url "sandbox:recipe_detail" recipe.id %}">{{ recipe.name }}</a>
          Description:
          <p>{{ recipe.description }}</p>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No refreshing recipe found.</p>
  {% endif %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Foodie</title>
  </head>

  <body>
    <nav>
      <div>
        <a href="{% url "foodie_app:index" %}">Foodie</a>
        <a href="{% url "foodie_app:add_recipe_no_genre" %}">Add Recipe</a>
      </div>
    </nav>
    <main>
      <div class="container">
        {% block content %}{% endblock content %}
      </div>
    </main>
    <div>
      <hr>
      <footer>
        <pre>footer</pre>
      </footer>
    </div>
  </body>

</html>